language: python
python:
  - "2.7"
sudo: false
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=src/sludge-sensor.cpp PLATFORMIO_CI_BOARDS_ARGS="--board huzzah"

install:
  - pip install -U platformio
  - platformio lib --global install ConfigManager@0.6

script:
  - platformio ci ${PLATFORMIO_CI_BOARDS_ARGS}
